### ISSUE TITLE
can't hidde taleView Line

### ISSUE THREAD

**Issue by chquanquan** [bay2/DZNEmptyDataSwift#2]
when I show the emptyView. there are so many tableView line.that i don't wanted. I used UITableViewController.help me. thanks
![2017-01-02 19 05 48](https://cloud.githubusercontent.com/assets/14248860/21588122/8ac66274-d11e-11e6-9e26-687bc536fe99.png)

**Comment by bay2** [comment]
Adding UIView to tableFooterView
tableView.tableFooterView = UIView()
