### ISSUE TITLE
同一个项目中不能同时使用collectionview和tableview

### ISSUE THREAD

**Issue by SeongBrave** [bay2/DZNEmptyDataSwift#3]
如果一个项目中，同时使用了collectionview 和tableivew 并且都用了空数据，这样的话，就会出问题，要嘛只在collectionview中显示要嘛只在tableview中显示空界面，你完了看看这是什么原因呢

**Comment by bay2** [comment]
@SeongBrave 这个问题，我刚刚提交的代码已经解决了，你可以试一下，在你那是否也是ok的

**Comment by SeongBrave** [comment]
恩恩，多谢了，我在看看
